language: cpp

compiler:
#  - clang
  - gcc

script: make

notifications:
   email: false


# The default is:
#     GCC 4.8.2 that supports C++11
#     Clang 3.5.0 taht supports C++11

#
# It takes about 6 minutes to install the required packages on Travis Server.
# 
#
# before_script:
#    - export CXX=g++-7
#
#script: make
#
#addons:
#    apt:
#        sources:
#            - ubuntu-toolchain-r-test
#        packages:
#            - g++-7

  
